### ISSUE TITLE
enquirer.register("list", ...) throws

### ISSUE THREAD

**Issue by AlCalzone** [enquirer/prompt-list#10]
```
TypeError: Cannot set property 'errorMessage' of undefined
index.js:14
    at Checkbox (d:\create-adapter\node_modules\prompt-checkbox\index.js:14:21)
    at Radio (d:\create-adapter\node_modules\prompt-radio\index.js:12:12)
    at List (d:\create-adapter\node_modules\prompt-list\index.js:12:9)
    at Enquirer.register (d:\create-adapter\node_modules\enquirer\index.js:52:28)
```
Debugging shows that `this` is `undefined` at the above location.

**Comment by jonschlinkert** [comment]
@AlCalzone this library going to be deprecated. It's not compatible with Enquirer 2.0, which includes this prompt by default - it has been renamed to `Select`. 

We have an [open issue](https://github.com/enquirer/enquirer/issues/28) about this, and have been preparing instructions on migrating over to Enquirer 2.0. I recommend using https://github.com/enquirer/enquirer directly. 

Sorry for the confusion.

**Comment by AlCalzone** [comment]
Ok thanks for the quick response! :+1:
